version: '3'

services:
    todoapp-backend:
        build: .
        volumes:
            - ./:/usr/src/app
        stdin_open: true
        depends_on: 
            - todoapp-backend-postgresql
        
    
    todoapp-backend-postgresql:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./.docker/dbdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: todoapp
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin